### ISSUE TITLE
Enable MyPy type checking in pre-commit hooks

### ISSUE THREAD

**Issue by mmiura-2351** [mmiura-2351/mc-server-dashboard-api#86]
## Summary
Enable MyPy type checking in pre-commit hooks to improve code quality and type safety. Currently disabled due to 78 type errors across 21 files that need to be resolved incrementally.

## Current Status
- MyPy is configured in `.pre-commit-config.yaml` but commented out
- 78 type errors identified across 21 files during initial setup
- Type checking runs manually via `uv run mypy app/` but not enforced in pre-commit

## Type Error Categories
Based on initial analysis, the main error types are:
- Missing return type annotations on functions
- Untyped function parameters
- Missing import stubs (particularly for `aiofiles`)
- Type compatibility issues in service integrations
- `Any` type returns where specific types are expected

## Acceptance Criteria
- [ ] Resolve all 78 existing type errors
- [ ] Add missing type annotations for function parameters and return types
- [ ] Install and configure missing type stubs (e.g., `types-aiofiles`)
- [ ] Update service integrations to use proper type hints
- [ ] Enable MyPy hook in `.pre-commit-config.yaml`
- [ ] Ensure all pre-commit hooks pass including MyPy

## Implementation Strategy
1. **Phase 1: Infrastructure**
   - Install missing type stubs packages
   - Fix import-related type errors
   - Address basic configuration issues

2. **Phase 2: Core Services**
   - Add type annotations to core services (database, authentication, etc.)
   - Fix service integration type compatibility issues
   - Address missing return type annotations

3. **Phase 3: Business Logic**
   - Add type annotations to routers and endpoints
   - Fix model and schema type consistency
   - Address remaining edge cases

4. **Phase 4: Validation & Enablement**
   - Verify all type errors are resolved
   - Test MyPy pre-commit hook functionality
   - Un-comment MyPy configuration in `.pre-commit-config.yaml`

## Files with Type Errors (Top Priority)
- `app/services/encoding_handler.py`
- `app/core/daemon_config.py`
- `app/middleware/performance_monitoring.py`
- `app/services/minecraft_api_service.py`
- `app/services/file_management_service.py`
- And 16 additional files

## Benefits
- Improved code quality and maintainability
- Early detection of type-related bugs
- Better IDE support and autocompletion
- Enhanced documentation through type hints
- Consistent type safety across the codebase

## Current MyPy Configuration
```yaml
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0
  hooks:
    - id: mypy
      additional_dependencies:
        - types-python-dateutil
        - types-requests
      exclude: ^(tests/ < /dev/null | migrations/)
      args: [--ignore-missing-imports, --scripts-are-modules, --no-strict-optional, --allow-untyped-defs, --allow-incomplete-defs, --no-warn-return-any, --allow-untyped-calls]
```

## Related
- This issue builds on the pre-commit hooks implementation in Issue #80
- Type safety improvements will support future refactoring efforts
- Enhanced developer experience through better tooling integration

## Priority
**Medium** - Important for long-term code quality but not blocking current functionality

## Labels
- enhancement
- technical-debt
